### ISSUE TITLE
On Press

### ISSUE THREAD

**Issue by snurre66** [athombv/com.ikea.tradfri#102]
When the dimmable_remote(2 button) is directly paired to a bulb we can continuously dim the bulb, when holding down the on or off button.

Since the remote can send "is pressed" commands to the bulb, is it possible the remote can also send these commands to homey...?

When there is only "when button have been pressed" and not "when button is still pressed" there is no possibility to make continuously dimming in homey flows.

It may not be possible anyway, since I am not a Homey veteran. If this is the case then please close this issue

**Comment by whome** [comment]
I think the terms should be clicked and hold/held/long pressed. 
But anyway I also think this should be good.

**Comment by RobinBol** [comment]
Thanks for reporting your issue, unfortunately continuous dimming the way you propose is not possible. However, it is possible to pair the remote to the bulb to use continuous dimming while also using the remote in your Flows (see our support article on this: https://support.athom.com/hc/en-us/articles/360015669840-How-do-I-directly-control-a-Zigbee-device-with-a-Zigbee-remote-).
