### ISSUE TITLE
'Zet helderheid' card jumps to 50% when moved

### ISSUE THREAD

**Issue by sanderv** [athombv/com.ikea.tradfri#11]
Scenario: 
- Set up a flow with a few cards in the '...dan' column and make sure at least one of them is a dimmable lamp (color temp and brightness). Not sure if this fails for the white lamp too.
- Set the brightness of the card to e.g. 10% (anything other than 50%)
- Move the card to another spot in the '...dan' column.

Expected: The brightness should remain at the set level
Actual: The brightness is set to 50%

**Comment by JPe2** [comment]
If you want the cards in the "dan" column to be started in a predefined order, it is not enough to place them in the wanted order, they will be started all at the same time, so you have to define different delays for each card.

**Comment by RobinBol** [comment]
Hi Sander, thanks for reporting your issue. This is a known problem, but not specific to the Ikea app. If you want you can create an issue here https://github.com/athombv/homey/issues. We are currently not fixing these small issues in the desktop app as we are working towards a brand new smartphone app which will replace the desktop app.
