### ISSUE TITLE
Enable new Tradfri models in App

### ISSUE THREAD

**Issue by Asinke** [athombv/com.ikea.tradfri#14]
Would it be possible to add these new? Tradfri bulbs to the App?
I'm looking to get the additional bulb functions, like dimming and color tone enabled.

![screen shot 2017-09-16 at 20 43 37](https://user-images.githubusercontent.com/32021588/30523928-aab1e51c-9bea-11e7-9ded-1385d592a655.png)

![screen shot 2017-09-17 at 20 59 48](https://user-images.githubusercontent.com/32021588/30523938-cf297518-9bea-11e7-9dcc-ea0a0d997d91.png)

**Comment by RobinBol** [comment]
The GU10 is added, what sort of bulb is the first? (As in, what capabilities does it have; only onoff and dim, or also light temperature?)

**Comment by Asinke** [comment]
Hi Robin,

Thanks for your swift response!
Please see below the package details for both the GU10 and E14 models requested.

Kind regards,

Arthur

GU10:
[cid:B2BCF8210970D3469B7159500B3F829B@sinkemojet.nl][IMG_2588.JPG]

E14:

[cid:1E17DD6142C9484ABE44EC7E720D72E1@sinkemojet.nl]


[cid:347B3438B2BF1A4098C44313F01D8C0F@sinkemojet.nl]


On 18 Sep 2017, at 21:11, Robin Bolscher <notifications@github.com<mailto:notifications@github.com>> wrote:


The GU10 is added, what sort of bulb is the first? (As in, what capabilities does it have; only onoff and dim, or also light temperature?)

**Comment by Asinke** [comment]
Just to be sure in case the pictures provided do not render correctly:
Both devices should support dimming and white color tone control.

**Comment by epjjansen** [comment]
@Asinke 
The GU10: Support dimming and white tone control
(From Ikea site:De lichtkleur kan variëren tussen 2200 Kelvin (warm licht), 2700 Kelvin (warmwit) en 4000 Kelvin (koudwit)).
The E14: Support dimming

**Comment by epjjansen** [comment]
URL to GU10 Product Ikea site: [http://www.ikea.com/nl/nl/catalog/products/00318292/](url)

**Comment by Asinke** [comment]
@epjjansen Any idea when to expect the updated App will be in the App store?

On 19 Sep 2017, at 08:57, epjjansen <notifications@github.com<mailto:notifications@github.com>> wrote:


@Asinke<https://github.com/asinke>
The GU10: Support dimming and white tone control
(From Ikea site:De lichtkleur kan variëren tussen 2200 Kelvin (warm licht), 2700 Kelvin (warmwit) en 4000 Kelvin (koudwit)).
The E14: Support dimming

**Comment by RobinBol** [comment]
Fixed in beta version of the app.

**Comment by epjjansen** [comment]
Works like a charm
