### ISSUE TITLE
Keep Direct Association remote/steering Device after Pairing Homey 

### ISSUE THREAD

**Issue by Dijker** [athombv/com.ikea.tradfri#18]
Reading the IKEA manuals (better looking at pictures) for what I understand it is possible to still use a remote after pairing the IKEA HUB.  (Not tested, correct me if I am wrong)

For what I experience with the TRADFRI 5 Button Remote (currently UNsupported with Homey) and the TRADFRI Rotating Dimmer (supported) this is not possible in combination with Homey. 

If I pair Homey I have to Reset the TradFri bulb or Float Panel and the remote is not functional anymore.
If I pair the remote I have to Reset the TradFri bulb or Float Panel and the Homey device is not functional anymore.
(Tested here this way with E27 bulp and Float Panel and both mentioned remotes.)
 
I would like to have this with Homey also working. 

Maybe this is due to a technical limitation or an absence of good documentation to implement. 
pls let us know....

If anyone has tips how to get it working pls reply!

(I trust Homey, but not always myself. Therefor I don't want to depend only on Homey and want some alternate control options.)

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2565
