### ISSUE TITLE
Unknown Zigbee device - Tradfri bulb E27 opal 1000lm

### ISSUE THREAD

**Issue by tinkerton** [athombv/com.ikea.tradfri#19]
<img width="815" alt="skarmavbild 2017-09-20 kl 14 38 27" src="https://user-images.githubusercontent.com/4364573/30644087-8403ba48-9e11-11e7-8325-5097dfea9bd1.png">

Can't get this product to show up as anything other than an Unknown Zigbee Device.

**Comment by epjjansen** [comment]
Try to update the firmware of the E27 bulb. You need a hub for this

**Comment by RobinBol** [comment]
Hi, do you have a link to the exact device you refer to? I need to know what it's capabilities are, e.g. onoff/dim/light_temperature etc.

**Comment by tinkerton** [comment]
I could try to update it as @epjjansen suggested. I think I connected this bulb directly to Homey without pairing it to the Ikea Hub first.

I bought a lot of lamps but I am pretty sure it is this lamp:
http://www.ikea.com/nl/nl/catalog/products/60338452/

on/off
Dimmable
Unsure of light temparture, but will inspect the bulb more closely once I come home.

**Comment by RobinBol** [comment]
Updating firmware is not necessary. I will add the bulb as onoff/dimmable for now, it you find out it has light_temperature as well let me know!
