### ISSUE TITLE
TRADFRI bulb E27 opal 1000lm support

### ISSUE THREAD

**Issue by Dijker** [athombv/com.ikea.tradfri#2]
Today I bought a "TRADFRI bulb E27 opal 1000lm" 
despite it isn't mentioned in the readme.md it works! (Above string reported from ZigBee Settings -Device information)

I also almost reported E12 and  E26 as non-existend, 
but I see they are used in other countries (most 110 Volt). https://nl.wikipedia.org/wiki/Edison-schroefdraad 

Don't know if it is a bug in the device name from IKEA or you shopped overseas  ;-)

**Comment by RobinBol** [comment]
Thanks for reporting, I added the bulb to the support devices list in the readme!
