### ISSUE TITLE
E14 Bulb not correctly detected

### ISSUE THREAD

**Issue by kallebjork** [athombv/com.ikea.tradfri#27]
Can pair but shows up as generic zigbee device. Not possible to dim, only on/off working. See screen shot for device information.

<img width="401" alt="screen shot 2017-09-25 at 19 06 55" src="https://user-images.githubusercontent.com/22211891/30821358-65cdbffc-a225-11e7-9e6d-f2d102a4dab7.png">

**Comment by RobinBol** [comment]
This device was added to the beta version of the Tradfri app.
