### ISSUE TITLE
 Ikea's five-button remote control

### ISSUE THREAD

**Issue by Turtures** [athombv/com.ikea.tradfri#29]
Hello!
Is there a possibility that Ikea's five-button remote control will be added
or are there limitations in the Homeys Zigbee protocol.....

/Tom D

**Comment by RobinBol** [comment]
Currently it is not possible, but we might look into this in the future.

**Comment by specialcircumstances** [comment]
This would be really great - interested to know what the issue is?

**Comment by Turtures** [comment]
Ok. good to know so you do not buy more of them

**Comment by matrover** [comment]
i would really like this too!

**Comment by r0n1n112** [comment]
Any news/update on the progress of adding the remote?
This is the 1 thing missing to fully utilize the Tradfri solution

**Comment by frostih** [comment]
Dear @RobinBol .  Please keep us updated on this one.  This really keeps all value of the Homey down as many of us have equipped our homes with IKEA's system.  I have purchased a Homey that supports Nexa components but there is no way I can adapt it to the IKEA lights around the house if the remote's don't function after pairing the bulbs to Homey.   For that same reason, I can't recommend Homey to anyone while it's unsolved.  

Alternative solution would be to support a remote that could replace the IKEA remotes, half the damage of course, but surely only temporary solution, not ideal.

With thanks for all so far!

F

**Comment by fredrikj83** [comment]
I agree, I think people would really appreciate some more transparency regarding various issues with the Homey and its apps. The feeling I keep getting is that the Homey is still in a beta stage. It would be interesting to know if you're simply having issues with resources or if it's a problem with the remote itself for some reason? Thanks in advance!

**Comment by RobinBol** [comment]
Hi all, thanks for your patience. If I would have had an update I would have let you know, the current state is the same is I mentioned in my initial comment. The reason for this is that the Ikea remotes do not work as we would expect (based on our experience with the ZigBee stack). We currently focus on the devices that can be controlled BY Homey (such as bulbs), eventually we might look into adding support for the remotes (but this is a long(-er) term plan).

**Comment by frostih** [comment]
Thanks for the answer RobinBol.  I understand that there is a problem with the remotes but is there no workaround to be able to use both, homey and the remotes (paired to the same bulb/s) ?  

Second (if you have a minute); Are there no plans to integrate to IKEA's tradfri gateway?  It would allow Homey to basically do all things requested with a simple API port from Homey.  

Best thanks for your efforts!

**Comment by RobinBol** [comment]
There likely is one indeed, but this needs further investigation so I can't really comment on that. There are no plans to create an app which communicates directly with Ikea Tradfri's gateway since Homey can communicate directly with the bulbs this does not add a lot of value. However, this might be a nice effort for a community developer?

**Comment by frostih** [comment]
Well, while you can't support IKEA's remotes, and you don't seem to have it in your future plans... the Tradfri support is almost useless to the normal users as nobody wants only to have control by using only Homey, we need physical buttons too!.  Even though the dimmer from IKEA is supported, it doesn't give direct access to the color control except through the app.  I recon that adapting to the gateway would fix this issue for now until you find a solution to the later in the future.  Till then, you should warn buyers of Homey that it doesn't support but half of the IKEA's functionality (one cannot deny that their 5 button remotes are a big part of the product funtionality)

**Comment by MrKoopie** [comment]
I agree with @frostih here. Although support for the light bulbs is awesome, supporting the remotes would be even better. Voice recognition does not work properly and is not wanted in every situation.

Alternatively different remotes can be used, but what remote does have 5 buttons?

**Comment by markvandeven** [comment]
For those that are really in need of a remote, [this cheap Xiaomi remote works](https://www.gearbest.com/access-control/pp_626695.html) with homey. The firmware supports single, double, triple and quadruple tapping so that you can bind 4 options to this device. Could be a good alternative while the remote function is not yet available..

**Comment by rnldnkp** [comment]
+1 on this one

The remote looks really nice, has a magnet to store it on a wall, but you're still able to take it with you.

Would really be a nice add-on to this app and would help to adopt Homey in an environment where not everybody is a tech guy/girl

**Comment by michelkamp** [comment]
for what is is worth , see below for the id's of the 5 button remote:
"type":string"EndDevice"
"ieeeAddr":string"0x90fd9ffffe15c5cd"
"nwkAddr":int889
"manufId":int4476
"manufName":string"IKEA of Sweden"
"powerSource":string"Battery"
"modelId":string"TRADFRI remote control"
"epList":[...]1 item
"status":string"offline"
"joinTime":NULL
"name":string"Onbekend ZigBee apparaat"
"profileId":string"49246"
"deviceId":string"2096"
"manufacturerName":string"IKEA of Sweden"
"productId":string"TRADFRI remote control"

**Comment by PeterHT** [comment]
For what it's worth (I don''t understand it) some swedish guy hacked the tradfri hub, saying it should work the same way for the 5-button-remote. May be helpfull?
https://www.youtube.com/watch?v=wS8Vj0ba4ic

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2564

**Comment by Franqqq** [comment]
Because https://github.com/athombv/homey/issues/2564 is archived my comment here.

Is there any news on this subject?

**Comment by o0donder0o** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/102

They seem to have figured out how to use the controller here. Does this mean we can expect progress on the Homey support for this remote as well?

**Comment by rnldnkp** [comment]
@o0donder0o this issue is closed a while ago. But there is another one: https://github.com/athombv/homey/issues/2564

**Comment by o0donder0o** [comment]
Thanks, didn't notice it was closed. Will ask my question over there.

**Comment by JeroenvdV** [comment]
The issue tracker where this was moved upon closing this issue, is now closed. Is this now once again the best place to discuss progress on support for the remote control?

I would like to see if I can contribute, but first I am trying to find out the current status.

**Comment by dolfje** [comment]
I would also like to know where to follow this bug. As I think the upstream issue is already fixed and released some time now.

**Comment by ZeppDK** [comment]
would be really nice to get this fixed, as ALL of my switches is ikea 5 button... this is forcing me to have atleaset 2 gateways... and that was not the plan when bying this verry expensive homey pro....

**Comment by JeroenvdV** [comment]
@RobinBol I'm most confused about a single place to find and discuss information regarding this issue, since things have moved around a bit since 2017. Can you comment on that?

I feel like this problem should either have a clear 'can't fix' resolution that can be monitored for changes to the underlying problem, or an open issue with some TODOs that the community could pick up if so inclined. @o0donder0o seems to indicate in March that there may be progress worth re-opening this issue for (on this issue tracker or elsewhere). I think it would be great if you could look into that and give the thread a bit of an update, or point me in the right direction :)
