### ISSUE TITLE
Tradfri 400Lm 5.3watt cabdle bulb not reqonized

### ISSUE THREAD

**Issue by B3rt** [athombv/com.ikea.tradfri#30]
The e14 candle bulb with product number 603.652.71 is not reqonized by homey as Ikea device but as  unknown zigbee device.

This results that it cannot be dimmed but only turned on/off.

Details:
Fabrikant ID: IKEA of Sweden
Product ID: TRADFRI bulb E14 W op/ch 400lm
Apparaat ID: 256
Profied ID: 49246

![2017-10-02_195437](https://user-images.githubusercontent.com/720614/31091536-99f1da9e-a7ab-11e7-9216-703733c5cf2d.png)

**Comment by RobinBol** [comment]
The app was just updated to support this bulb as well! Thanks for reporting.

**Comment by B3rt** [comment]
I got other bulbs from ikea, type 603.384.52 these are also not reqonized by the app or homey...

It is the Ikea Tradfri led 1000lm (12.5w) E27 2700kelvin bulb for 9,95
This is according Ikea a dimmable E27 bulb for the tradfri serie but no rgb, so no color change.

It has as productnumber 603.384.52
This is according to ikea the most sold bulb of the Tradfri serie (due to low price)

Homey cannot pair this buld, not by using the ikea app and also not as zigbee device.

**Comment by RobinBol** [comment]
I think you need to reset your bulb, all devices should be pairable as zigbee device, if not, then the device does not announce itself to Homey (which Homey can not fix). If you do not manage to reset your bulb please open a new issue.

**Comment by B3rt** [comment]
tried it, new bulb direct out of the box do not work.

When i try an other type it works fine, only these bulbs do really nothing, i got several of them and none of the work or are even reqonized

**Comment by RobinBol** [comment]
Are you able to reset the bulb as demonstrated in this video: https://www.youtube.com/watch?v=mJm9YpPrGzk?

The bulb needs to blink in the end to signal a successful reset.

**Comment by B3rt** [comment]
tried it but nothing happens....

Tried is exactly like as in video, nothing happens, there is also no 2 flashes after 6 times of/on.  
But i think this is normal because it is a new bulb which is not paired yet and so there is nothing to reset..

So resetting does not work..

Of course i tried it to add it again after resetting, but same result, homey does nothing: no zigbee device found.

I do not believe the bulb it the problem, 5 NEW bulbs at the same time defected is not very likely.....

**Comment by RobinBol** [comment]
That is not normal, you should always be able to reset a bulb, whether it was paired before or not. There were some more people claiming that a certain type of bulb could not be reset. Does the manual say anything about a reset/pair procedure?

**Comment by B3rt** [comment]
The manual of the bulb mention to reset:  
turn switch on/off 6 times (schakel de hoofdschakelaar 6 keer heen en weer.)

I opened also a topic on the forum, after a lot of trying etc i got 4 of 5 bulbs working after hours of trying, how i did it i do not now, just switching constantly on/off etc 
See here the topic: (i am B3rt) https://forum.athom.com/discussion/3961/ikea-tradfi-not-pairing-reqonized

Sadly the last bulb i ran out of luck, i simply cannot add or reset it, today i tried for 1.5 hour of switching on/off to reset or add it, nothing is happening :(

An other forum member/moderator (Rocodamelshe) purchased the same bulb that day and has exactly the same problem but he could without no problem add it to the IKEA controller.
He was also not able to pair it with homey, i myself do not have a IKEA controller only the IKEA bulbs, so i cannot confirm this.

So i do believe/suspect this is a app/driver/homey issue, not a bulb problem, therefor a bug.
