### ISSUE TITLE
ota upgrade tradfri bulbs

### ISSUE THREAD

**Issue by durd** [athombv/com.ikea.tradfri#33]
Easy issue this, will there be a possibility to upgrade tradfri bulbs firmware via Homey/this app?
With a conbee controller there seems to be possibility, once having the firmware file available.

[deConz release page with tradfri OTA support.](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_04_64)

**Comment by RobinBol** [comment]
This is probably not going to happen, but I'll leave the issue open for later reference. Thanks for reporting!

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2563
