### ISSUE TITLE
IKEAs motion sensor

### ISSUE THREAD

**Issue by durd** [athombv/com.ikea.tradfri#34]
Wouldn't mind being able to use IKEAs motion sensor with Homey.
I was able to add it as a general zigbee device, but that only gave an on/off control which did not do much of motion sensing. 

Thanks!

Edit: just saw the unsupported list of devices. Will they never be supported or is support on it's way?

**Comment by RobinBol** [comment]
The Ikea motion sensor does not follow the ZigBee specs as we would expect, hence we did not manage to make it work as of yet.

**Comment by alvarosanchez** [comment]
Any way we can contribute to its support?

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2562
