### ISSUE TITLE
e27 bulb isn't working

### ISSUE THREAD

**Issue by RosRoos** [athombv/com.ikea.tradfri#35]
Hello,

I have 2 e27 1000lm dimable bulbs and today i buyed a new e27 dimable bulb but i can't connect it to homey.
homey keeps searching for new bulbs.
a reset of the bulb doens't change anything.

its the same bulb as i buyed before.. the only thing diffrent is a small code on the bulb it self.
the bulb that doesn't work has: 1720-s1 
the bulb that works with homey has: 1647-s1

i hope you can help me?

Regards,

Ros

**Comment by RobinBol** [comment]
Hi Ros, when you try to reset the bulb does it flash once at end to indicate the reset has finished? See this video for instructions: https://www.youtube.com/watch?v=mJm9YpPrGzk

**Comment by synegic** [comment]
Hello Ros, I had the same issue you are facing right now. The IKEA E27 bulbs are very tricky to pair. You could try the following; https://github.com/athombv/com.ikea.tradfri/issues/4#issuecomment-326731685.

**Comment by RosRoos** [comment]
Yes indeed! it's done!
i needed to turn off all the bulbs before i connect a new one.
thanks for support!
