### ISSUE TITLE
Change in values not recognised

### ISSUE THREAD

**Issue by cbho** [athombv/com.ikea.tradfri#37]
Made a flow using values (the tags) from the Ikea-app (Bulb from item 703.389.51) that should trigger if any of the chosen values (hue, brightness, saturation, on/off etc.) changes to set values in a Fibare RGBW 
device.

When testing the flow, values are transferred without problems - but changing e.g. the hue of the Ikea bulb does not trigger the flow - although I can se values are changing when looking at the tags.

Tried both Logic and Bette Logic flow cards - but no difference.

Homey FW 1.5.5, Ikea-app 1.2.2

**Comment by jeroenvollenbrock** [comment]
Can you please send us a screenshot of a flow that does not work?

**Comment by cbho** [comment]
![image](https://user-images.githubusercontent.com/29979509/33024330-181a4b7e-ce0b-11e7-979d-8c27ea848b69.png)

**Comment by cbho** [comment]
Found the same error in another setting:
Using the tag #Motion alarm from a NEO Coolcam Motion Alarm doesn't trigger a flow as supposed to.

![image](https://user-images.githubusercontent.com/29979509/34072463-3c5c4b5e-e288-11e7-97da-26533e5e1b51.png)

**Comment by RobinBol** [comment]
I think the way you are creating your Flow is wrong. The 'tag' you put in the 'A variable changed' is not a variable as such. So it will never trigger, you should use the device card which has card such as 'turned on/off' and 'dim-level changed'. The real issue here is that the RGB bulbs do not have a saturation/hue has changed Flow trigger card. I will change the title accordingly.

**Comment by cbho** [comment]
Thanks - although I think "The real issue" is, that there are variables, that are not variables...
It seems illogical to me, that a tag that changes cannot be used as a trigger  upon the change - hue, dim, on/off, motion, whatever - it still is a variable, as it can take different values...
A lot of flows could be saved, if a general card "something changed" was introduced :-)
