### ISSUE TITLE
Dimmer behaviour

### ISSUE THREAD

**Issue by florpan** [athombv/com.ikea.tradfri#38]
Hi

I have read a lot of discussions about the dimmer being slow and unreponsive. And for me it was pretty much unusable compared to when pairing it directly to a lamp. 
Checking how the dimmer behaves it seems to have a constant dimming speed so i swapped out the debounce for a constant update using setInterval instead. This seems to work a lot better and is a lot more responsive. 
It is available in this fork https://github.com/florpan/com.ikea.tradfri

There are however implications to this approach, one being a separate interval per dimmer. so even though the code executed on each interval is slim, the number of dimmers in a system increases the total overhead. But im not sure of how the overall performance is effected by this aproach. It shouldn't be too bad, but that may be bad enough..
Are there any other timers available for operations like this? preferably one that is throttled when the dimmer is inactive? if that is even possible.

**Comment by florpan** [comment]
Hmm.. not sure if this is an issue anymore.. Just updated to the latest packages inc the meshdriver and after that it seems i can bind the dimmer and light to homey at the same time i have the dimmer bound to the light..

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2561
