### ISSUE TITLE
Status update light | light is ON but for homey it's still OFF or visa versa

### ISSUE THREAD

**Issue by Reemster** [athombv/com.ikea.tradfri#39]
![screenshot_20171129-164138](https://user-images.githubusercontent.com/19860405/33397421-dbb7c3d0-d54b-11e7-8a40-6ceb22116329.jpg)
Sometimes i have the problem that homey don't update the bulb/light status of a light. When i run the flow  with test, i see also the redcross.

I'm not sure exactly, but i have this issue only when Homey is online for a longer time. (say 2weeks and more) After the PTP it's working again. Also i can't turn off the light with the new Homey app. I get a error.

I'm using now Firmware Versie: 1.5.4. 
log: B0858C5254
![knipsel](https://user-images.githubusercontent.com/19860405/33397395-c9459a7e-d54b-11e7-95db-82f03210eb5b.JPG)

**Comment by RobinBol** [comment]
@Reemster when the Flow gives a red cross or the mobile app shows the error, does the bulb react? Or does it not respond to the command?

**Comment by Reemster** [comment]
No, it does nothing. Sometimes it helps when i turn off the power of the bulb for a short time. But maybe what the problem is, that i don't have a good zigbee network? Unfortunately i can't see how much signal the bulb has because i'm not an Athom Developer (it's weird that you guys remove that function btw)

**Comment by CootNL** [comment]
I need to restart homey every day to make the Ikea bulb working again.
The bulbs are not responding at all after the use of 1 day.

**Comment by Reemster** [comment]
So, a few weeks ago i replaced my KAKU switch because KAKU and homey don't work well together. I buy 2 Hue bulbs, and for the first time, i connect them to Homey directly (no bridge) and now i have the SAME problem what i have sometimes with the Ikea Bulb.... Homey don't see/update the right status... See screenshot. (The lights are **ON** when i make this screenshot) It's weird that i only have this with Zigbee devices, because i have never problems with Fibaro dimmer 2 devices..

 Can this bug please be found? 
Maybe you can see something in the logs? A6D921F68D

![hue light](https://user-images.githubusercontent.com/19860405/35644815-54857fbe-06ca-11e8-9ce3-6ec8c16adfd0.jpg)

**Comment by RobinBol** [comment]
Merging with: https://github.com/athombv/homey/issues/1956
