### ISSUE TITLE
TRADFRI bulb E27 opal 1000lm does not pair - workaround available

### ISSUE THREAD

**Issue by synegic** [athombv/com.ikea.tradfri#4]
Hello,

I seem to have some difficulties pairing TRADFRI E27 opal 1000lm bulbs, and it appears I am not alone. Whatever I try, it simply does not want to pair (6-click reset does not work, holding it so close it touches Homey does not work, etc). Other devices (like dimmer, GU10 bulbs) do seem to pair without any problems.

I did notice that on the IKEA site under manuals, there are two product numbers listed. LED1623G12 and LED1622G12. Mine has the product number LED1623G12, and I suppose may have another productId causing it not to show up while pairing.

Can you tell me how I can enable debugging mode on my Homey to check the productId this bulb is using? I already tried enabling debug mode in your app code from GitHub, hoping it would work the same as on z-wave, but that doesn't seem to work. I would really like to help, so just let me know how and I'll figure it out for you.

Link to comments on app page; https://apps.athom.com/app/com.ikea.tradfri#comment-598311c9acec78ed0d25298f

**Comment by RobinBol** [comment]
Hi, thanks for creating this issue. Can you describe what happens when the device won't pair? Does the pairing wizard timeout or is the device added as a 'basic/generic zigbee device'?

`TRADFRI bulb E27 opal 1000lm` is added as a productId so that should not be the issue, however you mention the device will not reset itself? It never blinks? Then this is very likely the issue, the bulb does not registers itself with Homey. Probably not something we can fix (most likely an issue with the bulb).

Could you try to pair the bulb a couple of times and then generate a log file for me? (Settings > System > Send a log). Then I can see if the device actually starts communicating with Homey or nothing happens.

**Comment by RobinBol** [comment]
BTW, I read in the App store thread that this seems to happen to bulbs that were paired with a dimmer out of the box, can you try to find in the manual of these devices how you can remove a bulb from the dimmer? Maybe after that it can be reset.

**Comment by synegic** [comment]
Hi Robin, I don't think it's an issue with the bulb; it does pair up nicely with the rotating dimmer and works with it flawlessly after that. I also don't think it can actually be caused by this (that it's already paired), because the first time I tried these bulbs they weren't paired to anything before I tried pairing them to Homey. All other Tradfri products do seem to work correctly. The reset procedure is actually the same according to the manual; off/on 6 times and then it should reset. If you watch the IKEA video for resetting the bulb, it actually does not flicker after reset. So I have no idea what's going on.

I'll have a look at the logs it generates tonight and see what I can find!

**Comment by RobinBol** [comment]
Hm oke, thought someone said they were bulbs that were sold packaged with the dimmer (then they are paired out of the box). Please let me know if you have more information!

**Comment by Mwahhh** [comment]
I bought 2, one in a box with a dimmer. The bulb isnt paired 'from the box'. I managed to get the one working that came with the dimmer but it was a hell of a job. Took me quite some time to get the first one paired with Homey. First I paired it with the dimmer, reset the bulb and after a couple of times trying to pair they did pair.  The second bulb (only bulb) is unpairable for me.

**Comment by synegic** [comment]
Seems to be something with the bulb after all. The following worked for me;

1. Pair bulb with steering device (rotating dimmer for example)
2. Reset dimming device
3. Reset bulb by toggling it off/on 6 times
4. Initiate add device sequence in Homey
5. Turn the bulb off/on 2 times

It should pair fine afterwards. Out of the box it just won't pair, whatever you try. So be advised; also get at least one steering device to get it ready to pair with Homey.

**Comment by Mwahhh** [comment]
Worked the second time. My issue is fixed, thanks!

**Comment by synegic** [comment]
Hmm, my workaround worked for two out of three bulbs I own. The last one really does not want to pair. Literally just spent an hour trying to make it work. Pairs fine with the rotating dimmer, but never wants to pair with Homey.

Really leaves a sour aftertaste. The 10 euro per smart bulb did seem too good to be true, apparently that is the case (takes a lot of effort/hit and miss). Ah well. ;-)

**Comment by casperboone** [comment]
Not a very useful contribution, but just to let you know: Experiencing the same issue here. Pairing 5 other type of lights went fine, but this one won't pair unfortunately.

**Comment by synegic** [comment]
I kept on trying to pair the remaining bulbs. Eventually all of them paired.

You could try resetting them with following steps; pair to steering device, control bulb to see if paired, bulb off (2 sec), reset steering device by clicking pair 4 times in 5 sec,  bulb off (5sec), bulb on (0.5sec), bulb off (2 sec), bulb on (0.5sec), bulb off (2 sec), bulb on (0.5sec), bulb off (2 sec), bulb on (0.5sec), bulb off (2 sec), bulb on (0.5sec), bulb off (2 sec), bulb on (0.5sec), bulb off (5 sec), start Homey add device wizard, bulb on.

Apparently it is very picky accepting a reset. The trick in my case was to have the bulb off longer than on in the reset sequence. Hope this'll help anyone also battling with these bulbs..

**Comment by RobinBol** [comment]
Thanks for the information! I will close this issue as the start issue seems to be solved for the user that reported it initially.

**Comment by nempnett** [comment]
For any other first timers - I was also struggling until the last comment of this thread. Synegic's 'longer off short on' pattern worked first time for me and then with three other bulbs in a row after an hour of failing before using this pattern. The bulb always blinks when it resets for me and if it does that will then always pair after switching on and back on again. I've paired bulbs on different floors to the hub - the 'hold close' advice seems less relevant to me than making sure of the reset. I did not have to pair with steering device at all.

**Comment by IvoDerksen** [comment]
Yes, I've encountered this issue as well.
Great to see the Athom community is a great help!

Using the instructions of Synegic I've also managed to pair my ignorant bulb.
In my case it did not flash twice, just count the times you toggle. 

Enhancement proposal:
Might want to add this instruction to the pair wizard, or a redirect to GitHub FAQ or Store page for instructions.

**Comment by fvhuizen** [comment]
Why is this issue closed ?? It's still an issue to add an E27 Bulb 1000 lm so it needs a solution. I tried all above several times and was busy with it for 3,5 hours and no pairing at all.

**Comment by no-replies** [comment]
Agreed - Cant get e27 1000lm to appear in bridge.

Perhaps some are prepared with steering device and that's causing the issue. Bulb reset, Adding new steering device, touchlink on app or api and the bulb dims but isn't appearing in bridge !!!

**Comment by nestor-patrikios** [comment]
The long-short tip from Synegic was very helpful and at least got my bulbs flashing to indicate reset. For the record, I found this sequence worked
Start On
Off (count 1, 2, 3, 4, 5), On (count 1)
Repeat 5 more times leaving On
This reliably delivers the acknowledgement. Pairing is still flaky with my Samsung Hub though and currently stuck on 3rd one.

Ikea: this is ridiculously fiddly. It's like an 80s video game. Please sort it out.

**Comment by hakanmarklund** [comment]
Unfortunately I found this thread too late, so I can't tell if Synegic's tip was helpful or not. But...
When I told my colleague, who's more into home automation than I am, about my problem with exactly these IKEA bulbs, he told me that he had the same problem, and when finding the right delay for resetting them, he managed to reset one out of four. But the third one couldn't be reset by turning it on/off no matter how hard he tried. As was the case with mine.

So, he tried something else. He already had this ConBee USB stick that together with a Raspberry PI make a Zigbee hub. It is running a software called deCONZ in which there are two buttons for opening an admin view for the hub. One is called "Phoscon App", which is the newer and better (according to him), and there's also a button for opening "Web App".
Opening the web app you can control nearby touchlink devices, and there's a red reset button. They need to be less than 50cm away from the hub.

That's how he managed to reset the non-working bulbs, including mine.

I found John Rucker's first comment in this thread very informative:
https://community.smartthings.com/t/dr-hue-is-in-and-the-bulbs-are-back-reset-hue-bulbs-to-factory/9856
Further down there's a screenshot of the web app interface and the touchlink screen.

The hardware was bought from here:
https://shop.dresden-elektronik.de/?___store=english

Another possible way to reset the bulbs could be through a Philips Hue hub. I don't own one, so I can't try that, but the Philips iOS app "Hue Lights" has an option to force Zigbee bulbs to join Hue hub through Touchlink and "low level networking commands".

Hopefully this helps someone.

**Comment by nestor-patrikios** [comment]
Just saw this post now - looks like great info and I have a Pi! Thanks.

**Comment by tskjoedt** [comment]
Had same issue. For me it worked to do the reset sequence while the app was in search mode.

Theory: When bulbs are reset, they stay open for business for a few seconds while blinking. After that, they "pause" for some moments; during this, the light is constant. Then they start fading up and down. Somewhere after the blinking has stopped, maybe in the fading phase, they stop accepting pairing requests.

**Comment by jeroenwienk** [comment]
Same issue here was finally able to do it using [https://www.youtube.com/watch?v=WVdJ2PeItbA](https://www.youtube.com/watch?v=WVdJ2PeItbA). Apparently trying it by hand causes some issues. Range was not an issue since it paired at about 3 meters and I used the default zigbee pairing which automatically found the Ikea bulb.

**Comment by brian32768** [comment]
I struggled with two new E12 400 LED 1649C5 but they eventually woke up. Be persistent would be my advice. When I tried again this morning both of them paired after only 5 or 10 more tries.
