### ISSUE TITLE
Add support for Trådfri wireless driver 

### ISSUE THREAD

**Issue by labanx** [athombv/com.ikea.tradfri#43]
Feature request to add support for Trådfri Wireless driver, these are new in 2018. 

Two versions
30W http://www.ikea.com/no/no/catalog/products/60342656/
10W http://www.ikea.com/no/no/catalog/products/50356187/

Tried adding the 30W edition as a generic zigbee device, but homey identifiys the unit as on off switch while it should support dimming.

**Comment by jeroenvollenbrock** [comment]
Could you post a screenshot of the device info in the device settings of the generic zigbee devices?

**Comment by JeroenM1** [comment]
Hello. 
Excuse me for interfering. But no screenshot provided and i need suppport for these new ikeadevices too. Here is a screenshot of the 10W variant i bought today.
![skarmklipp](https://user-images.githubusercontent.com/37906414/38095316-7d885530-3370-11e8-9e6b-0efa0ae71966.PNG)

/Jeroen

**Comment by JeroenM1** [comment]
Here´s a screenshot of the 30W transformer( Same info though ).
![skarmklipp](https://user-images.githubusercontent.com/37906414/38206624-6cb7c248-36ab-11e8-9fb2-3e44b50d456f.PNG)

**Comment by json81** [comment]
Any news?

**Comment by JohanBendz** [comment]
@json81 I added support for them in my fork.

**Comment by Patrick1610** [comment]
@JohanBendz how do I use your fork on My Homey?

**Comment by JohanBendz** [comment]
@Patrick1610 
Installing an App from Github requires a computer with a software for communication with Homey installed in a way that allows you to install Apps manually.

The instructions below require that you use a PC with Windows, but it is just as easy to use macOS or Linux.

The first time you install an app from Github you need to follow the entire instruction, after this you can skip to bullet 4 (no need to reinstall the node.js application every time).

*** Only the first time ***
1. Install Node.js from https://nodejs.org/en/
Select the recommended version and follow the installation instructions.
2. When the installation is complete, start a terminal window via the shortcut "Node.js Command Prompt" (on a MacOS / Linux you simply start a terminal window).
3. In the terminal window, type "npm install -g athom-cli" and then press 'Enter'
The software that communicates with your Homey is now installed on the computer.

***Each time***
4. In the terminal window, type "Athom login"
You are then prompted to visit https://go.athom.com/cli-login where you login with your usual Homey credentials to create an Account Token that you need to be able to login to your Homey from the terminal window.
5. Copy and paste the code you received on the webpage into the terminal window and press 'Enter'
You are now logged in to your Homey and it is time to install an App!
6. Download the app you want to install from Github, you do this by clicking the "Clone or Download" button on the Github page of the App you want to download. Select Download ZIP, save the file to a location on your computer and then unpack the ZIP file.
7. In the terminal window, change the directory to the one you just created when you unpacked the ZIP file. (eg CD \ Github \ App1)
8. Now type "Athom app install" to install the App or "Athom app run" to test it.
When using "Athom app run" the app will automatically uninstall after use (CTRL + C will halt the App).
9. If everything went well you now have the new app installed in Homey.


If you install an App from Github that is already installed from Athom Appstore the Github verson will replace the already installed version, keeping all your devices, settings and flows intact.

If you later choose to replace the Github version with a version from the Athom Appstore that works just as great without loosing any information or data.


Good luck and have fun trying out my fork! :)

**Comment by RobinBol** [comment]
Thanks to @JohanBendz support for the transformers has been added to the beta channel of the Ikea Tradfri app, please install and test it and let us know if you encounter any issues. If not it will be promoted to stable in some time!
