### ISSUE TITLE
Rotating dimmer delay and skip step dimming

### ISSUE THREAD

**Issue by igitlin** [athombv/com.ikea.tradfri#46]
I add Rotating Dimmer to Homey, but dimming occurs with a large delay and jerks, I tried to change the sensitivity in the settings, but still there is no smooth adjustment as if the dimmer is connected to the lamp directly. Also Value not in the tag list

**Comment by RobinBol** [comment]
Thank you for reporting your issue. Currently the App repository issue trackers are not being monitored, all (App related) issues should be reported at https://github.com/athombv/homey/issues. Alternatively, use the 'Report an issue' button on the App page in the Homey Apps store to create an issue at the correct location. This issue will be closed now, our apologies for the inconvenience.
