### ISSUE TITLE
Changing color of the RGB bulb in a flow turns the lamp on at 100% brightness

### ISSUE THREAD

**Issue by KRiZ-R** [athombv/com.ikea.tradfri#48]
Hello,

I am using homey version 1.5.12
IKEA Trådfri v. 1.2.2

I have multiple RGB Trådfri lamps.
When using the change color card in a flow, the lamp turns on at full brightness instead of previous brightness. All the other cards work fine and keep the lamp at previous brightness.

**Comment by RobinBol** [comment]
Thank you for reporting your issue. Currently the App repository issue trackers are not being monitored, all (App related) issues should be reported at https://github.com/athombv/homey/issues. Alternatively, use the 'Report an issue' button on the App page in the Homey Apps store to create an issue at the correct location. This issue will be closed now, our apologies for the inconvenience.
