### ISSUE TITLE
surported devices 

### ISSUE THREAD

**Issue by PenguinFreeDom** [athombv/com.ikea.tradfri#54]
Hi will you add support for the 5 button and pir sensor also.....i yes.....when do you think.....they will be surported ??

**Comment by RobinBol** [comment]
Thank you for reporting your issue. Currently the App repository issue trackers are not being monitored, all (App related) issues should be reported at https://github.com/athombv/homey/issues. Alternatively, use the 'Report an issue' button on the App page in the Homey Apps store to create an issue at the correct location. This issue will be closed now, our apologies for the inconvenience.
