### ISSUE TITLE
All lights not running longer

### ISSUE THREAD

**Issue by Strike2001** [athombv/com.ikea.tradfri#55]
since the morning all my devices do not turn on or off .

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RobinBol** [comment]
Thank you for reporting your issue. Currently the App repository issue trackers are not being monitored, all (App related) issues should be reported at https://github.com/athombv/homey/issues. Alternatively, use the 'Report an issue' button on the App page in the Homey Apps store to create an issue at the correct location. This issue will be closed now, our apologies for the inconvenience.
