### ISSUE TITLE
E14 light candle light

### ISSUE THREAD

**Issue by rjbaat** [athombv/com.ikea.tradfri#57]
Hi, 
I have 2 of these e14 lights but i cant get them to work. Are they not compatible yet? Since this are the candle versions?
https://m2.ikea.com/nl/nl/p/tradfri-led-lamp-e14-400-lumen-draadloos-dimbaar-warm-wit-kaarslamp-opaalwit-60365271/

If not can you please add them in the next app release?

**Comment by TechnoX** [comment]
https://github.com/athombv/com.ikea.tradfri/issues/30 

Same light as in this issue that is reported to be working? Maybe it isn't working anymore?

**Comment by TechnoX** [comment]
Looking at the source code here
https://github.com/athombv/com.ikea.tradfri/blob/master/app.json#L235
I found the product "TRADFRI bulb E14 W op/ch 400lm"
Where W op/ch stands for white opal chandelier, i.e. a candle light, just as you linked.

Have you tried to use the "Dimmable Bulb (E14)" in the app? 


It seems like the "TRADFRI bulb E14 W op/ch 400lm" is the only product under "Dimmable Bulb (E14)". Why not changing the icon to a candle light instead? It seems that the current icon confuses a lot of people.

**Comment by rjbaat** [comment]
Well i tried it with the dimable e14 normal bulb. But that didnt work. So i guess the candle e14 needs to be added again to the ikea homey app. I havent tried the zigbee app yet.

**Comment by emiedv** [comment]
Have the same problem, this light will not pair with the app. Tried the "Dimmable Bulb (E14)" but to no success.

**Comment by rvk519** [comment]
same issue here....the led1649c5 doesn't seem to connect to homey or the hue bridge...

**Comment by RobinBol** [comment]
Thank you for reporting your issue. Currently the App repository issue trackers are not being monitored, all (App related) issues should be reported at https://github.com/athombv/homey/issues. Alternatively, use the 'Report an issue' button on the App page in the Homey Apps store to create an issue at the correct location. This issue will be closed now, our apologies for the inconvenience.
