### ISSUE TITLE
Outlet text always says “On”

### ISSUE THREAD

**Issue by DIYglenn** [athombv/com.ikea.tradfri#58]
While it works fine, the text says “ On” even if the device is off.

**Comment by RobinBol** [comment]
Thank you for reporting your issue. Currently the App repository issue trackers are not being monitored, all (App related) issues should be reported at https://github.com/athombv/homey/issues. Alternatively, use the 'Report an issue' button on the App page in the Homey Apps store to create an issue at the correct location. This issue will be closed now, our apologies for the inconvenience.
