### ISSUE TITLE
Tunable white bulb won't change light temperature

### ISSUE THREAD

**Issue by nhassink** [athombv/com.ikea.tradfri#6]
Since the stable version (1.0.7) the tunable white bulb won't change color temperature anymore. The device is paired as a tunable bulb and shows the white color temperature controls but changing the temperature from either the mobile card or from a flow does not work. Changing brightness and turning on/off does work

**Comment by Dijker** [comment]
Same here on both tunable Bulbs.... also on App beta 1.0.8

**Comment by casperboone** [comment]
Tried it with the E14 and the GU10 and indeed changing the light temperature does not work.

**Comment by nhassink** [comment]
Seems fixed in 1.0.9

**Comment by Dijker** [comment]
Confirmed Fixed for me on two bulbs (E14 and E27)
@nhassink You can close is yourself below if you think it is fixed!

**Comment by casperboone** [comment]
Confirmed! 🎉

**Comment by nhassink** [comment]
Issue solved and confirmed in 1.0.9. Closing this issue. Thanks for the fix.
