### ISSUE TITLE
Please add support for the TRÅDFRI  Signal repeater

### ISSUE THREAD

**Issue by tenold** [athombv/com.ikea.tradfri#62]
Please add support for this device 
TRÅDFRI  Signal repeater
https://www.ikea.com/gb/en/products/lighting/smart-lighting/tr%C3%A5dfri-signal-repeater-art-80424255/

**Comment by JohanBendz** [comment]
https://github.com/athombv/com.ikea.tradfri/pull/63

**Comment by RobinBol** [comment]
This will be released shortly, thanks to @JohanBendz .
