### ISSUE TITLE
Problem pairing E14 and E27 tunable lamps

### ISSUE THREAD

**Issue by logicalshrapnel** [athombv/com.ikea.tradfri#65]
I have one bulb of each kind (both tunable), both show the same behavior.
1. Click to add device
2. Select IKEA Trådfri and the lamp type
3. Reset bulb to start pairing 
4. Lamp is found and pairing starts
5. When pairing finishes Homey App says that no applicable app was found and adds the device as a basic Zigbee device.
6. Lamp is added but only possible to turn on/off since it's not controlled through the IKEA Trådfri app.

I've tried this with both lamps multiple times. 
I have the Homey <20cm away from the lamps. 
I've tried with and without resetting the lamp. 
The lamps are reset (I.e. I get the blink after six consecutive toggles)
Lamps work fine when paired with IKEA remote.

Lamp details for E14 seen as:
Manufacturer ID: IKEA of Sweden
Product ID: TRADFRI bulb E14 WS opal 400lm
Device ID: 256
Profile ID: 260
Network Address: 0x000b.....

**Comment by RobinBol** [comment]
Thank you for your information, you seem to have a new device type. I have added the device id to the app (v1.2.14) which will be tested and released in the near future.

For future issues, please contact our support department, we are not actively checking these repositories for issues and/or support.

**Comment by logicalshrapnel** [comment]
Hello,

The E27 lamp is still not possible to add though the E14 worked perfectly. I tried contacting Athom support but the lamp has still not bed added despite it being almost a month ago. So I'm trying here instead.

Thanks!

Manufacturer ID: IKEA of Sweden
Product ID: TRADFRI bulb E27 WS[character rendered as ? on black background]opal 980lm
Device ID: 256
Profile ID: 260
Network Address: 0x000b57...
