### ISSUE TITLE
Dimmable Transformer 30W fails when trying to pair

### ISSUE THREAD

**Issue by bjarteolsen** [athombv/com.ikea.tradfri#66]
The Dimmable Transformer 30W fails when added. Ends up as an Unknown Zigbee device.

v1.2.14
Homey (early 2019) version 2.1.2
![Screenshot_20190606-175917_Homey](https://user-images.githubusercontent.com/39953733/59048515-4409d100-8886-11e9-8c84-602e5f4b701a.jpg)

**Comment by RobinBol** [comment]
Please contact support with the device information (you can find this in your device settings). As you saw when creating this issue, we are not monitoring these issues nor provide support on GitHub.

**Comment by ksvan** [comment]
I sent this to support as well, but believe reporting here is correct as well. Bug seems to be that device Id is right, but product id is TRADFRI driver 30w now, not transformer. Seems to have been fixed for the 10w earlier in app.json

**Comment by RobinBol** [comment]
30W driver support will be released in the next com.ikea.tradfri update.
