### ISSUE TITLE
Dimmable LED spot (new) can't be paired

### ISSUE THREAD

**Issue by Olliebertolli** [athombv/com.ikea.tradfri#76]
I have a new ikea led spot (transparent housing) dimmable which i cannot pair with Homey, the older version (white housing) is working properly.

**Comment by RobinBol** [comment]
Please send me a screenshot of the advanced configurations of your device when paired as 'unknown ZigBee' device to Homey.

For the future, please contact support@athom.com, these repositories are not actively monitored for issues.

**Comment by Designburo** [comment]
I already send it to support. Had the same problem.

**Comment by RobinBol** [comment]
Should be fixed in com.ikea.tradfri@1.4.2, if not please contact support.
