### ISSUE TITLE
Roller blinds won't completely open

### ISSUE THREAD

**Issue by lucasvdh** [athombv/com.ikea.tradfri#84]
The initial pull request for the roller blinds was made with the `windowcoverings_state`. In the current situation the blinds have the `windowcoverings_set` capability which allows you set the blinds to a specific percentage.

### The issue
The `windowcoverings_set` capability works fine in the beginning. But after a while it doesn't allow you to completely roll up the blinds because they have lost track of their own state.

When you've set a limit to which the blinds may roll down they will exceed this limit when you set the position to 100%. Similarly they will not roll up completely when you set the position 0%. If you open/close the blinds enough times the set limit will eventually go down further and further.

### Proposed solution
I think the solution would be as simple as re-adding the `windowcoverings_state` capability. This is because setting the state to `upOpen` causes the blinds to roll up completely, until the blind notices that it can't roll up further, thus resetting the state.

I don't think this capability would have to be presented as a ui action. As long as you've got the flow card action to set the state to `upOpen` you can prevent this unwanted behavior from happening.

**Comment by lucasvdh** [comment]
Another possible solution would be to write a separate case for when the `windowcoverings_set` capability receives a value of `0`. When this value is `0` you could just set the `windowcoverings_state` to `upOpen`.

**Comment by RobinBol** [comment]
Thank you for your issue! I think your comment is indeed the right solution to this problem. I'll have to see how to implement this, since it sort of breaks the cluster command/capability binding. I will create an issue on our internal issue tracker to address this.

**Comment by lucasvdh** [comment]
For anyone experiencing this issue, you can just use the buttons on the blind itself to completely open them again.

**Comment by RobinBol** [comment]
Fixed in com.ikea.tradfri@1.5.2.

**Comment by lucasvdh** [comment]
Noice
