### ISSUE TITLE
Add support for the new TRADFRI dimmer buttons

### ISSUE THREAD

**Issue by logicalshrapnel** [athombv/com.ikea.tradfri#86]
IKEA just released new TRADFRI dimmer buttons (square) that are perfect for controlling simple lights at a good price. Please note that while they are stated as on/off they have dimming capabilities when keeping on/off pressed. 
https://www.ikea.com/se/sv/p/tradfri-tradloes-dimmer-vit-70408595/

I'd be super happy if suport fro this could be added to the app.

Data for the device in homey app:
Manufacturer ID: IKEA of Sweden
Product ID: TRADFRI on/off switch
Device ID: 2080
Profile ID: 260

On back of device:
TYPE E1743 TRÅDFRI ON/OFF Switch

**Comment by RobinBol** [comment]
Hi! Thank you for requesting support for a device.

Currently the App repository issue trackers are not being monitored, all (App related) issues should be reported at https://github.com/athombv/homey/issues. Alternatively, use the 'Report an issue' button on the App page in the Homey Apps store to create an issue at the correct location.

Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
