### ISSUE TITLE
Signal repeater

### ISSUE THREAD

**Issue by micronikje** [athombv/com.ikea.tradfri#88]
When installing the signal repeater through the app you get the notification that there is no homey app and it will be installed as a simple zigbee device. Could that be fixed?
Thanks

**Comment by RobinBol** [comment]
Could you post the advanced device settings of this basic zigbee device?

**Comment by micronikje** [comment]
is this what you are looking for:

4:{15 items
"type":string"Router"
"ieeeAddr":string"0x14b457fffef75640"
"nwkAddr":int9632
"manufId":int4476
"manufName":string"IKEA of Sweden"
"powerSource":string"Mains (single phase)"
"modelId":string"TRADFRI Signal Repeater"
"epList":[2 items
0:int1
1:int242
]
"status":string"offline"
"joinTime":NULL
"name":string"Signaal begane grond "
"profileId":string"260"
"deviceId":string"8"
"manufacturerName":string"IKEA of Sweden"
"productId":string"TRADFRI Signal Repeater"
}

**Comment by RobinBol** [comment]
Yes, thank you. I will add support for your device in the coming update (com.ikea.tradfri@1.6.0). Next time, it is best to contact support@athom.com. We are not monitoring these repositories.

**Comment by micronikje** [comment]
Oké, Thank you for your support.

**Comment by RobinBol** [comment]
You can use [this link](https://homey.app/nl-nl/app/com.ikea.tradfri/IKEA-Tr%C3%A5dfri/test/) to install the test version of the Ikea Tradfri app to verify that you can pair the Signal Repeater correctly now.

**Comment by micronikje** [comment]
HI, I installed the app and could pair the signal repeater. it also is Still available as a simple zigbee device.
Now I am going to test if the repeater does work well. Thanks again.

________________________________
Van: Robin Bolscher <notifications@github.com>
Verzonden: Monday, November 25, 2019 11:52:36 AM
Aan: athombv/com.ikea.tradfri <com.ikea.tradfri@noreply.github.com>
CC: micronikje <micronikje@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [athombv/com.ikea.tradfri] Signal repeater (#88)


You can use this link<https://homey.app/nl-nl/app/com.ikea.tradfri/IKEA-Tr%C3%A5dfri/test/> to install the test version of the Ikea Tradfri app to verify that you can pair the Signal Repeater correctly now.
