### ISSUE TITLE
Voice commands missing for Tunable White Bulb - I didn't find lights to turn to white

### ISSUE THREAD

**Issue by Dijker** [athombv/com.ikea.tradfri#9]
Homey 1.5.0
IKEAI Tradfri App v1.0.9 
Two Tradfri Tunable White Bulbs
Dimming woks, Light temperature using Mobile App or device card work also

Ask Homey "zet de lamp op koud/warm wit"
Answer: Ik kon geen lampen vinden die op witte tinten gezet kunnen worden

//en:   I didn't find lights to turn to white

**Comment by RobinBol** [comment]
This is a known issue, not specific to the Ikea app, I created an issue for this on our internal issue tracker and will therefore close this one. Thanks for reporting!
