### ISSUE TITLE
Adding dimmer tradfri ikea art# 704.085.95

### ISSUE THREAD

**Issue by weusthofm** [athombv/com.ikea.tradfri#90]
Hello,

I bought the dimmer 704.085.95 for Tradfri last weekend. However in the app for homey this modules is not implemented yet. Properbly it is a brand new device, but so easy to use. could you add this device to the collection of tradfri devices.
thanks in advance.

Marcel

**Comment by pellz0r** [comment]
There has already been a issue created (and closed) for this (https://github.com/athombv/com.ikea.tradfri/issues/86).

Athom are not actively monitoring github so they want us to use https://go.athom.com/request-device-support to request support for new devices.

I have been waiting for added support for the Ikea rollerblind switch for half a year now without anything happening :(

**Comment by DeVisdude** [comment]
+1 for me aswell. I have made a request aswell

**Comment by DeVisdude** [comment]
Nothing is happening with this request, which is really frustrating...
Also worrying that the whole app isn't being updated at all
