### ISSUE TITLE
TRADFRI bulb E14 WS 470lm

### ISSUE THREAD

**Issue by ivom74** [athombv/com.ikea.tradfri#93]
hello
this device is not recognized by the app.

Can you add this new one? the simple e14 withyou can change only the lightning lumen is recognized but these new one not.
Do you need more info ?

**Comment by pahen** [comment]
Can confirm this. Here's some info about it:

<img width="1196" alt="Screenshot 2020-07-29 at 08 46 44" src="https://user-images.githubusercontent.com/353888/88766296-11045a00-d178-11ea-9c9e-fc8eb95ea659.png">

**Comment by RobinBol** [comment]
Thank you, fixed in com.ikea.tradfri@1.7.4, currently available in test (requires Homey v5.0.0 Experimental).
