### ISSUE TITLE
Add support for Tradfri Motion Sensor

### ISSUE THREAD

**Issue by RobinRadic** [athombv/com.ikea.tradfri#97]
Please add support for Tradfri Motion Sensor.
https://www.ikea.com/nl/nl/p/tradfri-draadloze-bewegingssensor-wit-70429913/

**Comment by RobinBol** [comment]
This is already added in v1.8.3, currently in [test](https://homey.app/nl-nl/app/com.ikea.tradfri/IKEA-Tr%C3%A5dfri/test/) and only available on Homey v5.0.0.
