### ISSUE TITLE
Add support for Symfonisk Remote Control

### ISSUE THREAD

**Issue by dirkg173** [athombv/com.ikea.tradfri#98]
Could you please add the Symfonisk RC?
It’s already available in the Homey deCONZ app.

https://www.ikea.com/de/de/p/symfonisk-fernbedienung-fuer-soundsystem-weiss-60370480/

**Comment by Bascht74** [comment]
Same wish here. That would be really great...

unknown device | 14:b4:57:ff:fe:66:2b:e3 | 45179 (B07B) | EndDevice | IKEA of Sweden | SYMFONISK Sound Controller

Sebastian

**Comment by dirkg173** [comment]
@Bascht74, they did it!

https://github.com/athombv/com.ikea.tradfri/pull/103/files

**Comment by RobinBol** [comment]
Thank you for creating this issue, we will take a look at the pull request in the future!
